[build]
  command = "npm run build"
  functions = "netlify/functions"
  publish = "dist"

[build.environment]
  NODE_VERSION = "20"

[functions]
  node_bundler = "esbuild"

[functions.esbuild]
  format = "cjs"
  target = "node20"

[functions."process-image"]
  timeout = 26

[dev]
  command = "npm run dev"
  targetPort = 3000
  port = 8889
  publish = "dist"
  autoLaunch = false